//! Managed media files. Temporary files are owned by tempfile until completion.
use crate::model::ChatId;
use anyhow::{Context, Result, bail};
use std::{
    path::{Path, PathBuf},
    time::SystemTime,
};
use tempfile::TempPath;

const MAX_FILES: usize = 512;
const MAX_BYTES: u64 = 1024 * 1024 * 1024;

pub(super) async fn prepare(
    root: PathBuf,
    account: i64,
    owner: Option<std::sync::Arc<std::fs::File>>,
) -> Result<PathBuf> {
    tokio::task::spawn_blocking(move || {
        let _owner = owner;
        let directory = root.join(account.to_string());
        for path in [&root, &directory] {
            std::fs::create_dir_all(path)?;
            let metadata = std::fs::symlink_metadata(path)?;
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                bail!("media cache must be a real directory");
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))?;
            }
        }
        // The account cache lock guarantees these cannot belong to another
        // running instance. Cleanup happens before the first transfer starts.
        for entry in std::fs::read_dir(&directory)? {
            let entry = entry?;
            if entry.file_type()?.is_file() && is_partial(&entry.path()) {
                std::fs::remove_file(entry.path())?;
            }
        }
        prune(&directory, None, MAX_FILES, MAX_BYTES)?;
        Ok(directory)
    })
    .await?
}

pub(super) fn temporary(directory: &Path) -> Result<TempPath> {
    Ok(tempfile::Builder::new()
        .prefix(".tg-download-")
        .suffix(".part")
        .tempfile_in(directory)?
        .into_temp_path())
}

pub(super) async fn finish(
    mut temporary: TempPath,
    directory: PathBuf,
    chat: ChatId,
    message: i32,
    name: &str,
    owner: Option<std::sync::Arc<std::fs::File>>,
) -> Result<PathBuf> {
    loop {
        let path = super::unique_download_path(&directory, chat, message, name).await?;
        match temporary.persist_noclobber(&path) {
            Ok(()) => {
                let keep = path.clone();
                tokio::task::spawn_blocking(move || {
                    let _owner = owner;
                    prune(&directory, Some(&keep), MAX_FILES, MAX_BYTES)
                })
                .await??;
                return Ok(path);
            }
            Err(error) if error.error.kind() == std::io::ErrorKind::AlreadyExists => {
                temporary = error.path;
            }
            Err(error) => return Err(error.error).context("could not finish media cache file"),
        }
    }
}

// This suffix is generated by this module, not a user-selected extension.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
fn is_partial(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.starts_with(".tg-download-") && name.ends_with(".part"))
}

fn prune(directory: &Path, keep: Option<&Path>, max_files: usize, max_bytes: u64) -> Result<()> {
    let mut files = Vec::new();
    let mut bytes = 0_u64;
    for entry in std::fs::read_dir(directory)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() || is_partial(&entry.path()) {
            continue;
        }
        let metadata = entry.metadata()?;
        bytes = bytes.saturating_add(metadata.len());
        files.push((
            metadata.modified().unwrap_or(SystemTime::UNIX_EPOCH),
            entry.path(),
            metadata.len(),
        ));
    }
    files.sort_by_key(|(time, _, _)| *time);
    let mut count = files.len();
    for (_, path, size) in files {
        if count <= max_files && bytes <= max_bytes {
            break;
        }
        if keep == Some(path.as_path()) {
            continue;
        }
        match std::fs::remove_file(path) {
            Ok(()) => {
                count = count.saturating_sub(1);
                bytes = bytes.saturating_sub(size);
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn retention_preserves_partial_and_current_files_without_overwriting() {
        let root = tempfile::tempdir().unwrap();
        let directory = prepare(root.path().join("media"), 7, None).await.unwrap();
        let old = directory.join("old.txt");
        std::fs::write(&old, "old").unwrap();
        let active = temporary(&directory).unwrap();
        std::fs::write(&active, "partial").unwrap();
        let complete = temporary(&directory).unwrap();
        std::fs::write(&complete, "done").unwrap();
        let path = finish(complete, directory.clone(), 42, 1, "file.txt", None)
            .await
            .unwrap();
        let another = temporary(&directory).unwrap();
        std::fs::write(&another, "next").unwrap();
        let second = finish(another, directory.clone(), 42, 1, "file.txt", None)
            .await
            .unwrap();
        assert_ne!(path, second);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "done");
        prune(&directory, Some(&second), 1, 4).unwrap();
        assert!(second.is_file());
        assert!(active.is_file());
        assert!(!old.exists());
        assert!(!path.exists());
        let interrupted = active.keep().unwrap();
        prepare(root.path().join("media"), 7, None).await.unwrap();
        assert!(!interrupted.exists());
        assert!(second.is_file());
    }
}
